# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainCircus.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(331, 305)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.choosetype = QtWidgets.QComboBox(self.centralwidget)
        self.choosetype.setGeometry(QtCore.QRect(10, 10, 311, 22))
        self.choosetype.setObjectName("choosetype")
        self.delButton = QtWidgets.QPushButton(self.centralwidget)
        self.delButton.setGeometry(QtCore.QRect(230, 240, 91, 23))
        self.delButton.setObjectName("delButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(10, 240, 91, 23))
        self.addButton.setObjectName("addButton")
        self.changeButton = QtWidgets.QPushButton(self.centralwidget)
        self.changeButton.setGeometry(QtCore.QRect(120, 240, 91, 23))
        self.changeButton.setObjectName("changeButton")
        self.objView = QtWidgets.QListView(self.centralwidget)
        self.objView.setGeometry(QtCore.QRect(10, 40, 311, 192))
        self.objView.setObjectName("objView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 331, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "База данных цирка"))
        self.delButton.setText(_translate("MainWindow", "Delete"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.changeButton.setText(_translate("MainWindow", "Change"))
