# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WidgetPerformance.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PerformanceForm(object):
    def setupUi(self, PerformanceForm):
        PerformanceForm.setObjectName("PerformanceForm")
        PerformanceForm.resize(391, 374)
        self.label_13 = QtWidgets.QLabel(PerformanceForm)
        self.label_13.setGeometry(QtCore.QRect(140, 10, 111, 21))
        self.label_13.setObjectName("label_13")
        self.nameEdit = QtWidgets.QLineEdit(PerformanceForm)
        self.nameEdit.setGeometry(QtCore.QRect(160, 40, 221, 20))
        self.nameEdit.setObjectName("nameEdit")
        self.producerEdit = QtWidgets.QLineEdit(PerformanceForm)
        self.producerEdit.setGeometry(QtCore.QRect(160, 70, 221, 20))
        self.producerEdit.setObjectName("producerEdit")
        self.prod_designerEdit = QtWidgets.QLineEdit(PerformanceForm)
        self.prod_designerEdit.setGeometry(QtCore.QRect(160, 100, 221, 20))
        self.prod_designerEdit.setObjectName("prod_designerEdit")
        self.cond_directorEdit = QtWidgets.QLineEdit(PerformanceForm)
        self.cond_directorEdit.setGeometry(QtCore.QRect(160, 130, 221, 20))
        self.cond_directorEdit.setObjectName("cond_directorEdit")
        self.authorEdit = QtWidgets.QLineEdit(PerformanceForm)
        self.authorEdit.setGeometry(QtCore.QRect(160, 160, 221, 20))
        self.authorEdit.setObjectName("authorEdit")
        self.genreEdit = QtWidgets.QLineEdit(PerformanceForm)
        self.genreEdit.setGeometry(QtCore.QRect(160, 190, 221, 20))
        self.genreEdit.setObjectName("genreEdit")
        self.typeEdit = QtWidgets.QLineEdit(PerformanceForm)
        self.typeEdit.setGeometry(QtCore.QRect(160, 220, 221, 20))
        self.typeEdit.setObjectName("typeEdit")
        self.err_msg = QtWidgets.QLabel(PerformanceForm)
        self.err_msg.setGeometry(QtCore.QRect(90, 270, 211, 20))
        self.err_msg.setText("")
        self.err_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.err_msg.setObjectName("err_msg")
        self.label = QtWidgets.QLabel(PerformanceForm)
        self.label.setGeometry(QtCore.QRect(90, 40, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(PerformanceForm)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 131, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(PerformanceForm)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 131, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(PerformanceForm)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 131, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(PerformanceForm)
        self.label_5.setGeometry(QtCore.QRect(110, 160, 47, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(PerformanceForm)
        self.label_6.setGeometry(QtCore.QRect(110, 190, 47, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(PerformanceForm)
        self.label_7.setGeometry(QtCore.QRect(120, 220, 47, 21))
        self.label_7.setObjectName("label_7")
        self.okButton = QtWidgets.QPushButton(PerformanceForm)
        self.okButton.setGeometry(QtCore.QRect(60, 320, 91, 23))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(PerformanceForm)
        self.cancelButton.setGeometry(QtCore.QRect(240, 320, 91, 23))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(PerformanceForm)
        QtCore.QMetaObject.connectSlotsByName(PerformanceForm)

    def retranslateUi(self, PerformanceForm):
        _translate = QtCore.QCoreApplication.translate
        PerformanceForm.setWindowTitle(_translate("PerformanceForm", "Performance form"))
        self.label_13.setText(_translate("PerformanceForm", "Заполните данные"))
        self.label.setText(_translate("PerformanceForm", "Название:"))
        self.label_2.setText(_translate("PerformanceForm", "Режиссер-постановщик:"))
        self.label_3.setText(_translate("PerformanceForm", "Художник-постановщик:"))
        self.label_4.setText(_translate("PerformanceForm", "Дирижер-постановщик:"))
        self.label_5.setText(_translate("PerformanceForm", "Автор:"))
        self.label_6.setText(_translate("PerformanceForm", "Жанр:"))
        self.label_7.setText(_translate("PerformanceForm", "Тип:"))
        self.okButton.setText(_translate("PerformanceForm", "OK"))
        self.cancelButton.setText(_translate("PerformanceForm", "Отмена"))
