# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WidgetPerformanceTroupe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PerformanceTroupeForm(object):
    def setupUi(self, PerformanceTroupeForm):
        PerformanceTroupeForm.setObjectName("PerformanceTroupeForm")
        PerformanceTroupeForm.resize(391, 323)
        self.err_msg = QtWidgets.QLabel(PerformanceTroupeForm)
        self.err_msg.setGeometry(QtCore.QRect(90, 220, 211, 20))
        self.err_msg.setText("")
        self.err_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.err_msg.setObjectName("err_msg")
        self.okButton = QtWidgets.QPushButton(PerformanceTroupeForm)
        self.okButton.setGeometry(QtCore.QRect(60, 270, 91, 23))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(PerformanceTroupeForm)
        self.cancelButton.setGeometry(QtCore.QRect(240, 270, 91, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.performanceEdit = QtWidgets.QLineEdit(PerformanceTroupeForm)
        self.performanceEdit.setGeometry(QtCore.QRect(160, 40, 221, 20))
        self.performanceEdit.setObjectName("performanceEdit")
        self.label_3 = QtWidgets.QLabel(PerformanceTroupeForm)
        self.label_3.setGeometry(QtCore.QRect(90, 100, 61, 21))
        self.label_3.setObjectName("label_3")
        self.surnameEdit = QtWidgets.QLineEdit(PerformanceTroupeForm)
        self.surnameEdit.setGeometry(QtCore.QRect(160, 70, 221, 20))
        self.surnameEdit.setObjectName("surnameEdit")
        self.label = QtWidgets.QLabel(PerformanceTroupeForm)
        self.label.setGeometry(QtCore.QRect(70, 40, 81, 21))
        self.label.setObjectName("label")
        self.roleEdit = QtWidgets.QLineEdit(PerformanceTroupeForm)
        self.roleEdit.setGeometry(QtCore.QRect(160, 160, 221, 20))
        self.roleEdit.setObjectName("roleEdit")
        self.nameEdit = QtWidgets.QLineEdit(PerformanceTroupeForm)
        self.nameEdit.setGeometry(QtCore.QRect(160, 100, 221, 20))
        self.nameEdit.setObjectName("nameEdit")
        self.label_13 = QtWidgets.QLabel(PerformanceTroupeForm)
        self.label_13.setGeometry(QtCore.QRect(140, 10, 111, 21))
        self.label_13.setObjectName("label_13")
        self.label_4 = QtWidgets.QLabel(PerformanceTroupeForm)
        self.label_4.setGeometry(QtCore.QRect(60, 130, 91, 21))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(PerformanceTroupeForm)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 91, 21))
        self.label_2.setObjectName("label_2")
        self.patronymicEdit = QtWidgets.QLineEdit(PerformanceTroupeForm)
        self.patronymicEdit.setGeometry(QtCore.QRect(160, 130, 221, 20))
        self.patronymicEdit.setObjectName("patronymicEdit")
        self.label_5 = QtWidgets.QLabel(PerformanceTroupeForm)
        self.label_5.setGeometry(QtCore.QRect(76, 160, 81, 21))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(PerformanceTroupeForm)
        QtCore.QMetaObject.connectSlotsByName(PerformanceTroupeForm)

    def retranslateUi(self, PerformanceTroupeForm):
        _translate = QtCore.QCoreApplication.translate
        PerformanceTroupeForm.setWindowTitle(_translate("PerformanceTroupeForm", "Performance troupe form"))
        self.okButton.setText(_translate("PerformanceTroupeForm", "OK"))
        self.cancelButton.setText(_translate("PerformanceTroupeForm", "Отмена"))
        self.label_3.setText(_translate("PerformanceTroupeForm", "Имя актёра:"))
        self.label.setText(_translate("PerformanceTroupeForm", "Представление:"))
        self.label_13.setText(_translate("PerformanceTroupeForm", "Заполните данные"))
        self.label_4.setText(_translate("PerformanceTroupeForm", "Отчество актёра:"))
        self.label_2.setText(_translate("PerformanceTroupeForm", "Фамилия актёра:"))
        self.label_5.setText(_translate("PerformanceTroupeForm", "Название роли:"))
